### PR TITLE
Why is Travis failing?

### PR DESCRIPTION
**Pull request by dpc10ster**
https://api.travis-ci.org/v3/job/549430122/log.txt

Passes R CMD check on my machine

### CODE REVIEW

**Comment by pwep** [comment]
Looking at the Travis log for build 193, the failing test is as follows:
```
── 1. Failure: known hash (@test-compare-3fits.R#24)  ──────────────────────────
Value hashes to ee6f623095, not 6a90170dda
```

The `expect_known_hash` test at the end of `test-compare-3fits.R` is till there in the `master` branch.
https://github.com/dpc10ster/RJafroc/blob/fa6db3965c53c49976b7435174c424e7b1f6d524/tests/testthat/test-compare-3fits.R#L19-L24

I will let you delete these lines from `test-compare-3fits.R` in the `development` branch, and merge the development branch into `master`. (No point generating a pull request for this fix)

**Comment by pwep** [comment]
I note your comment on commit 47ee231
```
# unfortunately this causes Failures on Travis; differences are in the 6th decimal place
```
...and that difference will be why the hash value on Travis does not match the hash value hard-coded as an argument to `expect_known_hash` in `test-compare-3fits.R`

**Comment by dpc10ster** [comment]
You explained it all so well; thank you and I will not ruin your weekend
any further; Dev

**Comment by dpc10ster** [comment]
Pull request successfully merged and closed
You’re all set—the development branch can be safely deleted.

I did not delete it

**Comment by pwep** [comment]
> I did not delete it

Quite right. Changes get their own named branch, which get pulled into the development branch via pull request. When you are happy that development branch is ready for release to the wider public, you merge changes into the master branch.

**Pull request merged**
