### PR TITLE
Updates to RJafroc

### PR DESCRIPTION
**Pull request by dpc10ster**
1. I have pushed my edits to the `testthat` folder. With about 560 tests, I believe it is time to move on to CRAN submission process and final testing. The main work remaining here is to bring the standard of the code in all test files to that in `test-significance-testing.R` which I can do for the next submission.

1. Can you review the `DESCRIPTION` file? Particularly the authors. You have played a critical part in this project and I want to give you full credit. Also, please review the `cran-comments.md` and summarize your fixes to the Solaris problem? And the `README.md` - I need to include your contributions here. All edits will be much appreciated. No rush, just give me a general idea.

1. `RJafroc` passes all tests on my OSX machine but did generate an unusual warning, which is not listed in the final summary as a warning; strange; the relevant lines are shown below in my next comment

1. Can you run tests on your machines?

1. When you feel it is appropriate, I suggest another Skype call, as some things are best discussed that way.

1. I replaced `options(warn = 2)` but closed that file (`Compare3RocFits.R`) with a final call with `options(warn = 0)`

### CODE REVIEW

**Comment by dpc10ster** [comment]
This is the output of the R CMD check on my machine, with the offending lines quoted:

==> Rcpp::compileAttributes()

* Updated R/RcppExports.R

==> devtools::check(args = c('--no-build-vignettes'))

Updating RJafroc documentation
Writing NAMESPACE
Loading RJafroc
Writing NAMESPACE
── Building ─────────────────────────────────────────────────────────────────── RJafroc ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
──────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/Users/Dev/RJafroc/DESCRIPTION’ ...
─  preparing ‘RJafroc’: (2.7s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
✔  creating vignettes (48.1s)
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (735ms)
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘RJafroc_1.1.1.9000.tar.gz’
   
── Checking ─────────────────────────────────────────────────────────────────── RJafroc ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
● _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
● _R_CHECK_CRAN_INCOMING_           : FALSE
● _R_CHECK_FORCE_SUGGESTS_          : FALSE
── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/Users/Dev/RJafroc.Rcheck’
* using R version 3.6.0 (2019-04-26)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --no-build-vignettes --as-cran’
* checking for file ‘RJafroc/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘RJafroc’ version ‘1.1.1.9000’
* package encoding: UTF-8
* checking package namespace information ... OK

> *** checking package dependencies ...Warning: unable to access index for repository https://CRAN.R-project.org/src/contrib:
>   cannot open URL 'https://CRAN.R-project.org/src/contrib/PACKAGES'
>  OK**
> * checking if this is a source package ... OK

* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘RJafroc’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ [304s/307s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
   ‘Ch00V1DataFormat.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch10V1QuickStartDBMH.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch10V2QuickStartDBMHExcel.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch11V1SampleSize.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch11V2SampleSize.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch11V3SampleSize.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch11V4SampleSize.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch11V5SampleSize.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch20V1improperROCs.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch20V2degenerateROCs.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch20V3proprocROCs.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch20V4metzEqn36.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch20V5cbmPlots.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch30V1RoiParadigm.Rmd’ using ‘UTF-8’ ... OK
   ‘Ch30V2RoiParadigmSt.Rmd’ using ‘UTF-8’ ... OK
 NONE
* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: OK

── R CMD check results ───────────────────────────────── RJafroc 1.1.1.9000 ────
Duration: 7m 24.6s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

R CMD check succeeded

**Comment by pwep** [comment]
Thanks Dev. I have been following the updates in your development branch over the last day or two. I will test on my machines tomorrow. I'll take a look at your other points over the next few hours.

**Comment by pwep** [comment]
```
*** checking package dependencies ...
Warning: unable to access index for repository https://CRAN.R-project.org/src/contrib:
    cannot open URL 'https://CRAN.R-project.org/src/contrib/PACKAGES'
 ```
CRAN servers are down (an IP issue I believe). This would account for the error **and** the timeout on the Travis build. Might be worth waiting until CRAN servers are accessible again before making any more changes based on Travis feedback.

**Comment by dpc10ster** [comment]
Thanks; I will try again tomorrow; Dev

**Comment by pwep** [comment]
Happy to Skype at some point over the next few days - I will make sure my Skype is switched when I am available.

**Comment by pwep** [comment]
> Also, please review the `cran-comments.md` and summarize your fixes to the Solaris problem?

The `cran-comments.md` file mentions a few of the errors I have seen, but as pointed out, they are known bugs.

Solaris fix: Renamed RJafroc C++ `erf` function, so as not to clash with an existing function in C++ library with the same name.

**Comment by pwep** [comment]
Commit 9b622ff fails for me. There is a difference in decimal places and rounding. The test fail output is shown below.

```
test-compare-3fits.R:15: failure: Compare3ProperRocFits
`Compare3ProperRocFits(1, 1, reAnalyze = TRUE)` has changed from known value recorded in './tempValues/Compare3ProperRocFits01'.
110/3061 mismatches
x[16]: "-3.085018  0.763543  1.331231  1.816872  2.415074 "
y[16]: "-3.085020  0.763543  1.331231  1.816872  2.415074 "

x[43]: "                  mu      lambdaP           nuP        zeta1       zeta2"
y[43]: "                  mu      lambdaP          nuP        zeta1       zeta2"

x[44]: "mu       0.079491666  0.006651657 -0.0057395067  0.120288482 0.020959236"
y[44]: "mu       0.079491665  0.006651656 -0.005739507  0.120288433 0.020959235"

x[45]: "lambdaP  0.006651657  0.017861919 -0.0023488117  0.234434954 0.003210050"
y[45]: "lambdaP  0.006651656  0.017861915 -0.002348812  0.234434854 0.003210048"

x[46]: "nuP     -0.005739507 -0.002348812  0.0055748260  0.002969605 0.001663961"
y[46]: "nuP     -0.005739507 -0.002348812  0.005574826  0.002969603 0.001663961"
```

**Comment by dpc10ster** [comment]
Thanks for this; it passed my Travis and local tests; this function uses
MLE which can converge to slightly different values as randomness is
involved; I will try setting a seed and if that doesn't work I will abandon
expect_known_output for this test;

**Comment by pwep** [comment]
Is it tested by Travis?

https://github.com/dpc10ster/RJafroc/blob/9b622ffae631b36d8689e46a18aa317ea44ff563/tests/testthat/test-compare-3fits.R#L4

I think the test might be skipped.  
<https://www.rdocumentation.org/packages/testthat/versions/2.1.1/topics/skip>

**Comment by dpc10ster** [comment]
You are absolutely right; it hangs up Travis due to long computation time; so it probably would have failed; could you try the new one with fixed seed = 1?

**Comment by pwep** [comment]
Test fail again here with the same rounding and decimal place errors.
I think we need a more detailed test to step through the values (or groups of values) in the output object, using expect_equal to overlook any rounding error.  
<https://www.rdocumentation.org/packages/testthat/versions/2.1.1/topics/equality-expectations>

**Comment by pwep** [comment]
Differences in Compare3ProperRocFits01 can be found here:

<https://gist.github.com/pwep/619a823c7d2d4d4dfc489e73bcdec83c/revisions>

**Comment by dpc10ster** [comment]
I am going to push shortly; could you test out new version; i expect it to pass

**Comment by pwep** [comment]
Errors, but this time only of file length on `CompareProperRocFits01` and `CompareProperRocFits02`.

`CompareProperRocFits01` does not contain the complete `$allBinnedDatasets[[1]]$NL` array
I have an error in the file on line 1813.
` [ reached getOption("max.print") -- omitted 85 matrix slice(s) ]`

**Comment by dpc10ster** [comment]
OK; I am giving up on this approach; thanks for trying them out on Windows, I presume; 
dev

**Comment by pwep** [comment]
All tests performed on Linux with R 3.6.0, run with `devtools::test()`

**Comment by dpc10ster** [comment]
Thanks for update;

**Comment by pwep** [comment]
`CompareProperRocFits02` has extra lines, based on how `$allDatasetsResults[[1]][[8]]$retCbm$covMat` is written to the file. Difference between files is shown at:
<https://gist.github.com/pwep/d3d50bd94a33ea951aa8e59b7e65d563/revisions>

There must be  line-length default which is different on your platform compared to mine.

**Comment by dpc10ster** [comment]
I agree; I am coming to the conclusion that expect_known_output() is NOT
one of Hadley Wickham's more useful creations

I can't tell you how much time I have wasted on it.

Actually, if I removed the covariance matrices from the final output, not a
difficult step, that might (??) solve the problem; should I waste some more
time? ha ha

Dev

**Comment by pwep** [comment]
I'll have a look at the `testthat` API about checking equality across _objects_, rather than files. If we have an R data file we know is correct, there must be a way of loading it, and checking new output against it (within certain tolerances.)

**Comment by dpc10ster** [comment]
OK; BTW, I am using 4 character extensions in some of the saved “good value” files in Git (for later comparison); will that break in some operating systems? I know if will break in Windows XP

**Comment by pwep** [comment]
Office uses 4 character extensions for well-known file types: `.docx`, `.xlsx`, etc. Windows XP should handle it (and other operating systems too).

**Comment by pwep** [comment]
Saving an R object as as an RDS file should be safe across platforms.

I have created a small example file which outlines the approach. Very similar to what we have already, but the testing files are in RDS format.

<https://gist.github.com/pwep/a8f35093e40c228e91d0d90b90c235bd>

Files such as `CompareProperRocFit01` in the  `goodValues` directory would be saved as RDS files. A `testthat` test would `readRDS()` that file into memory. A simple `expect.equal(..., tolerance=0.00001)` would be able to check the `goodValues` version against the test-generated version.

**Comment by pwep** [comment]
One test fails on Linux:

```
✖ |   5 1     | Fitting routines [1607.0 s]
──────────────────────────────────────
test-fitting.R:97: failure: FitRsmRoc
FitRsmRoc(dataset02, UtilLesionDistribution(dataset02))[1:8] not equal to `ret`.
Component "mu": Mean relative difference: 3.865783e-08
Component "lambdaP": Mean relative difference: 2.563811e-08
Component "zetas": Mean relative difference: 2.05855e-07
──────────────────────────────────────
```
A tolerance value in `test-fitting.R` will fix it.

**Comment by dpc10ster** [comment]
Thanks; I applied your fix and will push soon;

Travis failed for developer version of R.

I am attaching the log file; the relevant part appears to be as follows: I think I need to set attribute explicitly; is that your understanding?



Running the tests in â€˜tests/testthat.Râ€™ failed.
Last 13 lines of output:
  Component "ciDiffTrtRRRC": Component "Estimate": Attributes: < target is NULL, current is list >
  Component "ciDiffTrtRRRC": Component "Estimate": target is numeric, current is array
  Component "ciAvgRdrEachTrtRRRC": Component "StdErr": Attributes: < target is NULL, current is list >
  Component "ciAvgRdrEachTrtRRRC": Component "StdErr": target is numeric, current is array
  Component "ciAvgRdrEachTrtRRRC": Component "DF": Attributes: < target is NULL, current is list >
  Component "ciAvgRdrEachTrtRRRC": Component "DF": target is numeric, current is array
  Component "ciDiffTrtFRRC": Component "Treatment": Attributes: < target is NULL, current is list >
  ...
  
  OK: 165 SKIPPED: 6 WARNINGS: 0 FAILED: 1
  1. Failure: StSignificanceTestingCrossedModalities (@test-significance-testing.R#105)

**Comment by dpc10ster** [comment]
Replacing expect_equal with expect_equivalent may fix this problem as it
ignores attributes in testing equality. I have just pushed.

**Comment by dpc10ster** [comment]
Closing this pull request after running on all 20 platforms on rhub

**Comment by dpc10ster** [comment]
merged development branch into master

**Pull request merged**
