### PR TITLE
Solaris fix

### PR DESCRIPTION
**Pull request by dpc10ster**
I am attempting to incorporate the changes and Solaris fix submitted by Peter Philips peter.phillips@cumbria.ac.uk; this is the first time I have done it so I am not sure what will happen; trusting GitHub will permit undoing any damages; if this works then I will run tests at my end.

### CODE REVIEW

**Comment by dpc10ster** [comment]
merging with master branch; Peter, it would help if we Skyped; Dev

**Comment by pwep** [comment]
I had not sent this branch through as a pull request yet. I had updated the DESCRIPTION file with my email as I have been using [r-hub](https://builder.r-hub.io) to build tests on Solaris. I'd like to see the package back on CRAN, and have a bit of time available to investigate the problem. I had hoped the C++ changes would have fixed the problem.

**Comment by dpc10ster** [comment]
Hi Peter,

I am glad you are working on it! I am relatively new at GitHub too and am
not familiar with the kosher collaboration process. Hopefully we can work
it out. My direct email is dpc10ster@gmail.com and I have the following for
you: peter.phillips@cumbria.ac.uk

Best regards.

Dev

**Comment by pwep** [comment]
Excellent. You have got my email address correct. I will set up a virtual machine to run Solaris if there is no quick fix to getting RJafroc back on CRAN.

**Comment by dpc10ster** [comment]
> I am attempting to incorporate the changes and Solaris fix submitted by Peter Philips [peter.phillips@cumbria.ac.uk](mailto:peter.phillips@cumbria.ac.uk); this is the first time I have done it so I am not sure what will happen; trusting GitHub will permit undoing any damages; if this works then I will run tests at my end.

# Please ignore this comment

**Pull request closed without merging**
