### PR TITLE
Add simple tests using the testthat package

### PR DESCRIPTION
**Pull request by pwep**
- `testthat` is already suggested in `DESCRIPTION`
- a `tests` directory and `testthat.R` file has been created
- aim to have tests for all major R functions, grouped by R file name
- some tests check a function correctly issues an error
- use `devtools::test()` to run the tests within R

### CODE REVIEW

**Comment by dpc10ster** [comment]
> * `testthat` is already suggested in `DESCRIPTION`
> * a `tests` directory and `testthat.R` file has been created
> * aim to have tests for all major R functions, grouped by R file name
> * some tests check a function correctly issues an error
> * use `devtools::test()` to run the tests within R

- `testthat` is suggested in `DESCRIPTION` as I was using `testthat` until something changed (R version?) and some of the tests started failing. 

- I show one example in my update to the development branch today (June 21, 2019 about 6 PM EDT). The function I focused on is `Compare3ProperRocFits()` which generates the most complicated output. Using `hash` as comparison the test works, but using the suggested `expect_known_output()` it does not. 

- I do not understand Hadley's comment that the file should be generated under Git control. On OSX the `tempfile` is created in a directory definitely not under Git control; I tried both ways - using the example code for this function and explicitly specifying the temporary file directory - neither worked.

Should we use the hash method and forget about the detailed comparison of all output?

**Comment by pwep** [comment]
I can see you have added some helpful tests, that exceed anything I offer here in this pull request!

I have created an issue in your repository (#6) relating to `expect_known_output()` and a pull request (#7) that I believe fixes the issue.

You might want to close this pull request without merging, as my offered tests are simplistic, and you have (re)added extensive tests to this development branch. There will be other potential issues that need to be solved, based on the messages coming from your tests.

**Comment by pwep** [comment]
In fact I shall close the pull request now.

**Comment by dpc10ster** [comment]
Thanks. I added the tests ~ Dec 2018 leading up to my last successful CRAN upload. I removed them recently, as some of them started failing for reasons that I have yet to resolve. I will continue working on making all tests pass, perhaps using the `hash` as a quick fix. I intend to create a small reproducible example showing the failure of `testthat` (specifically function `expect_known_output`) that I will pose to the R developer community. Dev

**Comment by dpc10ster** [comment]
> On Jun 21, 2019, at 20:20, Peter Phillips <notifications@github.com> wrote:
> 
> I can see you have added some helpful tests, that exceed anything I offer here in this pull request!
> 
> I have created an issue in your repository (#6 <https://github.com/dpc10ster/RJafroc/issues/6>) relating to expect_known_output() and a pull request (#7 <https://github.com/dpc10ster/RJafroc/pull/7>) that I believe fixes the issue.
> 
> 

I missed this. I am going to look into it right now.

**Pull request closed without merging**
