### PR TITLE
Cran3

### PR DESCRIPTION
**Pull request by dpc10ster**
I have updated the `cran-comments.md` file on `cran3` branch; can you review?

### CODE REVIEW

**Comment by pwep** [comment]
There is a merge conflict for this pull request on the following files:
```
tests/testthat/test-PlotEmpiricalOperatingCharacteristics.R
tests/testthat/test-predicted-plots.R
```

`cran3` is missing the `tests` directory. The test files were removed in commit 83e4116c60fccbb9151a8695e0345da472e0c04c on the `cran3` branch. Merging with `developer` branch (in commit aed6d3ebbfabce474f25e96156c0245aa9d47ebf) did not add them back in.

Should the test directory files be there for the merge into `master`?

**Comment by pwep** [comment]
From `cran-comments.md`

```
17. "ubuntu-rchk", Ubuntu Linux 16.04 LTS, R-devel with rchk:
    - ERROR too many states (abstraction error?) in function strptime_internal
```

This looks to be an error with the way rchk modules certain functions. I will look to isolate the error by running the  `ubuntu-rchk` image locally.

**Comment by dpc10ster** [comment]
Thanks; someday you have teach me about docker files and how to run these checks on your local computer; 

If this is not on the CRAN check listt, we can move on. (I dont see it.)

Dev

**Comment by dpc10ster** [comment]
Since all tests have been removed from `cran3`, should we just delete the coverage `yaml` file? That would remove the check failures, right?

**Comment by dpc10ster** [comment]
* I should have explained my workflow better; this is more for my info and recall: 
* It is all one-way: `developer` -> `master` -> `cran3`
* Then remove `doc`, `docs`, `tests` and `vignettes` from `cran3`. 
* Change DESCRIPTION file to remove `knits` and `rmarkdown` etc. 
* All this to get the file size down from 16.7Mb to 5.1Mb. 
* The package is too big for CRAN.

**Comment by pwep** [comment]
To resolve the merge conflict, I will delete the following files in `master`:
```
tests/testthat/test-PlotEmpiricalOperatingCharacteristics.R
tests/testthat/test-predicted-plots.R
```
These two files would have been deleted anyway.

**Comment by dpc10ster** [comment]
Do I really want to merge `cran3` (the stripped down version) into `master`? I was just going to use your comments on `cran3` to make the CRAN submission. Can you just tell me your changes on the cran3 branch so I can incorporate them into my submission.

**Comment by dpc10ster** [comment]
I got your changes on `cran3` branch. Plan to submit Monday. If you have any more changes ...

**Comment by dpc10ster** [comment]
I don't understand why I am missing the two files you made the fixes on with `check.environment = FALSE` in the `maste`r branch, but they are present in the `developer` branch, but when I try to merge from `developer` it says it is up to date with `master`?

**Comment by pwep** [comment]
It is a good question. Looking in the network diagram at <https://github.com/dpc10ster/RJafroc/network> a few things have happened. I've added a screenshot below.

The `developer` branch (in blue) was merged into `master` (black) and `cran3` (gold) at point 1 on the image below.

At point 2 my pull request (green) adding `check.environment = FALSE` was merged into `developer` and then into `master`. It did not make it into `cran3`, and I think in the meantime `cran3` deletes these files. These gives the merge error in this pull request, which is trying to merge `cran3` into `master`.

Screenshot 2020-12-12 at 01 06 03

> they are present in the developer branch, but when I try to merge from developer it says it is up to date with master?

Nothing new has been changed in the `developer` branch since the last merge into `master` (point 2 on the network above), so it is `to to date`.

**Comment by pwep** [comment]
> It is all one-way: `developer` -> `master` -> `cran3`

So this pull request is going in the wrong direction? It is trying to merge from `cran3` into `master`.

Looking again at your comment above....

> Do I really want to merge cran3 (the stripped down version) into master?

I guess the answer is no, so it might be an idea to close this pull request without the merge into master. 
I've been trying to honour the intention of the pull request (hence deleting those files from master to allow the merge).

**Comment by dpc10ster** [comment]
Thanks for the insight; I am relieved. Any suggestions on improved workflow, for future submits, are welcome; I will wait till Monday to submit to CRAN. Thanks!

**Comment by dpc10ster** [comment]
Will wait till Monday to submit;

**Pull request closed without merging**
